site_name: Introducción a la Nube
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "UD01. Introducción a la Nube Pública": 
      - "Introducción a la Nube Pública": "ud01/ud01.md"
      - "Lanzamiento del Laboratorio": "ud01/practica00.md"
      - "La Interfaz de Línea de Comandos": "ud01/practica01.md"
  - "UD02. Capa de Cómputo": 
      - "Capa de Cómputo": "ud02/ud02.md"
      - "Creación de una Máquina Virtual": "ud02/practica1.md"
      - "Prácticas a entregar": "ud02/practica2.md"
  - "UD03. Creación de un entorno de red": 
      - "Creación de un entorno de red": "ud03/vpc.md"
      - "Práctica 0. Creación de una VPC automática": "ud03/redpractica00.md"
      - "Práctica 1. Creación de una VPC manual": "ud03/redpractica01.md"
      - "Práctica 2. Creación de una VPC con 2 subredes": "ud03/redpractica02.md"
      - "Práctica 3. Creación de una VPC con CLI": "ud03/redpractica04.md"
  - "UD04. Capa de Almacenamiento": 
      - "Capa de Almacenamiento": "ud04/ud04.md"
      - "Práctica 1. Creación de bucket en S3": "ud04/practica1.md"
      - "Práctica 2. Publicación de una web estática en S3": "ud04/practica2.md"
      - "Práctica 3. Gestión de volúmenes EBS": "ud04/practica3.md"
      - "Práctica 4. Almacenamiento compartido con EFS": "ud04/practica4.md"
      - "Práctica 5. CI/CD con GitHub Actions sobre S3": "ud04/practica5.md"
  - "Proyectos":
      - "Infraestructura segura de servidores": "pr01/pr01.md"
      - "Vpc con Subredes y Base de datos RDS": "pr01/pr02.md"
  - "UD05. Capa de Base de Datos":
      - "Capa de base de datos": "ud05/ud5.md"
      - "Práctica 1. Base de datos con acceso público": "ud05/bdpractica01.md"
      - "Práctica 2. Base de datos privada": "ud05/bdpractica02.md"
      - "Práctica 3. Clúster de Base de Datos Aurora": "ud05/bdpractica03.md"
      - "Práctica 4. Base de datos NoSQL": "ud05/bdpractica04.md"
  - "UD06. Microservicios y arquitectura sin servidor":
      - "Microservicios y arquitectura sin servidor": "ud06/ud06.md"
      - "Práctica 1. Hello Lambda!": "ud06/practica1.md"
      - "Práctica 2. Función Lambda con url de activación": "ud06/practica2.md"
      - "Práctica 3. Función Lambda con desencadenador": "ud06/practica3.md"
      - "Práctica 4. Función Lambda con parámetros": "ud06/practica4.md"
      - "Práctica 5. Función Lambda con API Gateway": "ud06/practica5.md"
      - "Práctica 6. Función Lambda con API Gateway y DynamoDB": "ud06/practica6.md"
  - "UD07. Modelo de seguridad en AWS":
      - "Modelo de seguridad en AWS": "ud07/ud07.md"
  - "UD08. Monitorización en AWS":
      - "Monitorización en AWS": "ud08/ud08.md"
      - "Práctica 1. Métricas en EC2": "ud08/practica1.md"
      - "Práctica 2. Alarmas en Cloudwatch": "ud08/practica2.md"
      - "Práctica 3. Logs en Cloudwatch": "ud08/practica3.md"

theme:
    language: es
    name: "material"
    favicon: "images/cloud-computing.png"
    palette:
        - scheme: default
          primary: indigo
          accent: "light blue"
          toggle:
            icon: material/toggle-switch-off-outline
            name: Cambiar a modo noche
        - scheme: slate 
          primary: indigo
          accent: "light blue"
          toggle:
            icon: material/toggle-switch
            name: Cambiar a modo día
    font:
        text: Roboto
        code: Roboto Mono
    logo: "images/cloud-computing.png"
    features:
        - header.autohide
        - navigation.top
        - navigation.tracking
        - navigation.footer
        - navigation.indexes
        - content.code.annotate
        - announce.dismiss
        - toc.follow
        - content.code.copy

extra_css:
  - css/extra.css

extra:
  search:
    language: "es"

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
